# Generated by Django 5.0 on 2024-01-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employees',
            table='employees',
        ),
    ]
