# Generated by Django 5.0 on 2024-01-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employees_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employees',
            table=None,
        ),
    ]
